import type { Metadata } from 'next'
import './globals.scss'

import { SidebarProvider } from '@/components/ui/sidebar'
import Sidebar from '@/components/app-sidebar'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'bg-(--background-secondary)! '
        )}
      >
        <SidebarProvider className='px-[15]'>
          <main
            className={cn(
              'flex gap-2.5',
              'h-screen w-full py-[15] '
            )}
          >
            <Sidebar />
            <div className={cn('w-full p-7.5',
              'bg-(--background-primary) border border-(--border-default)',
              'rounded-[15] overflow-auto'
            )}>
              {children}
              </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
